const mongoose = require('mongoose');
const University = require('../models/University');
const VisaRequirement = require('../models/VisaRequirement');

const objectId = (hex) => new mongoose.Types.ObjectId(hex);

const seedData = async () => {
  const uri = 'mongodb://127.0.0.1:27017/study_abroad';

  try {
    await mongoose.connect(uri, {
      serverSelectionTimeoutMS: 10000,
      socketTimeoutMS: 45000,
    });

    console.log('✅ Connected to MongoDB for seeding');

    await University.deleteMany({});
    await VisaRequirement.deleteMany({});
    await mongoose.connection.db.collection('ai_tools').deleteMany({});

    const universities = [
      {
        _id: objectId('64f000000000000000000001'),
        name: 'University of Oxford',
        country: 'United Kingdom',
        city: 'Oxford',
        description: 'A world-renowned research university in the United Kingdom with strong programs in humanities, sciences, and social sciences.',
        website: 'https://www.ox.ac.uk',
        courses: ['Computer Science', 'Economics', 'Physics', 'Biology'],
        ranking: 1,
        fees: 28000,
        currency: 'GBP',
        logo: '',
        eligibility: { min_cgpa: 3.5, ielts: 7.0, gre: 0, entry_test: 'No' },
        visa_time: '4 Weeks',
        applicationDeadline: null,
        scholarships: ['Global Merit Scholarship', 'Oxford International Scholarship'],
        living_cost: 12000,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000002'),
        name: 'University of Cambridge',
        country: 'United Kingdom',
        city: 'Cambridge',
        description: 'A historic and highly selective university known for excellence in science, mathematics, and the humanities.',
        website: 'https://www.cam.ac.uk',
        courses: ['Mathematics', 'Physics', 'History', 'Computer Science'],
        ranking: 3,
        fees: 26000,
        currency: 'GBP',
        logo: '',
        eligibility: { min_cgpa: 3.6, ielts: 7.0, gre: 0, entry_test: 'No' },
        visa_time: '4 Weeks',
        applicationDeadline: null,
        scholarships: ['Cambridge Trust Scholarship', 'International Scholarship'],
        living_cost: 13000,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000003'),
        name: 'Harvard University',
        country: 'United States',
        city: 'Cambridge',
        description: 'A prestigious Ivy League institution offering world-class education in business, law, engineering, and public policy.',
        website: 'https://www.harvard.edu',
        courses: ['Business Administration', 'Computer Science', 'Law', 'Public Policy'],
        ranking: 2,
        fees: 56000,
        currency: 'USD',
        logo: '',
        eligibility: { min_cgpa: 3.8, ielts: 7.5, gre: 320, entry_test: 'Optional' },
        visa_time: '6 Weeks',
        applicationDeadline: null,
        scholarships: ['Need-Based Fellowship', 'International Student Scholarship'],
        living_cost: 18000,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000004'),
        name: 'Stanford University',
        country: 'United States',
        city: 'Stanford',
        description: 'A leading innovation-focused university with strong startup ecosystems and top programs in engineering and computer science.',
        website: 'https://www.stanford.edu',
        courses: ['Computer Science', 'Engineering', 'Business', 'Data Science'],
        ranking: 4,
        fees: 58000,
        currency: 'USD',
        logo: '',
        eligibility: { min_cgpa: 3.7, ielts: 7.0, gre: 320, entry_test: 'Optional' },
        visa_time: '5 Weeks',
        applicationDeadline: null,
        scholarships: ['Knight-Hennessy Scholars', 'Stanford Need-Based Aid'],
        living_cost: 17000,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000005'),
        name: 'Technical University of Munich',
        country: 'Germany',
        city: 'Munich',
        description: 'One of Europe’s leading technical universities with strong engineering and computer science programs.',
        website: 'https://www.tum.de',
        courses: ['Mechanical Engineering', 'Computer Science', 'Electrical Engineering', 'Data Science'],
        ranking: 20,
        fees: 15000,
        currency: 'EUR',
        logo: '',
        eligibility: { min_cgpa: 3.0, ielts: 6.5, gre: 0, entry_test: 'No' },
        visa_time: '5 Weeks',
        applicationDeadline: null,
        scholarships: ['Deutschland Scholarship', 'TUM International Scholarship'],
        living_cost: 11000,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000006'),
        name: 'Ludwig Maximilian University of Munich',
        country: 'Germany',
        city: 'Munich',
        description: 'A prestigious public university known for medicine, law, and humanities with a strong international student community.',
        website: 'https://www.lmu.de',
        courses: ['Medicine', 'Law', 'Psychology', 'Economics'],
        ranking: 35,
        fees: 12000,
        currency: 'EUR',
        logo: '',
        eligibility: { min_cgpa: 3.2, ielts: 6.5, gre: 0, entry_test: 'No' },
        visa_time: '5 Weeks',
        applicationDeadline: null,
        scholarships: ['LMU International Scholarship', 'Deutschlandstipendium'],
        living_cost: 10500,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000007'),
        name: 'University of Toronto',
        country: 'Canada',
        city: 'Toronto',
        description: 'A leading Canadian university with excellent industry partnerships, diverse campuses, and strong research output.',
        website: 'https://www.utoronto.ca',
        courses: ['Engineering', 'Data Science', 'Public Health', 'Business'],
        ranking: 18,
        fees: 32000,
        currency: 'CAD',
        logo: '',
        eligibility: { min_cgpa: 3.2, ielts: 6.5, gre: 0, entry_test: 'No' },
        visa_time: '5 Weeks',
        applicationDeadline: null,
        scholarships: ['International Scholar Award', 'U of T Excellence Scholarship'],
        living_cost: 14000,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000008'),
        name: 'University of British Columbia',
        country: 'Canada',
        city: 'Vancouver',
        description: 'A highly ranked research university known for sustainability, engineering, and innovative healthcare programs.',
        website: 'https://www.ubc.ca',
        courses: ['Engineering', 'Environmental Science', 'Commerce', 'Computer Science'],
        ranking: 40,
        fees: 30000,
        currency: 'CAD',
        logo: '',
        eligibility: { min_cgpa: 3.3, ielts: 6.5, gre: 0, entry_test: 'No' },
        visa_time: '6 Weeks',
        applicationDeadline: null,
        scholarships: ['UBC International Leader Award', 'Global Scholarship'],
        living_cost: 15000,
        isActive: true,
      },
      {
        _id: objectId('64f000000000000000000009'),
        name: 'University of Melbourne',
        country: 'Australia',
        city: 'Melbourne',
        description: 'Australia’s leading university with strong global recognition in health, business, and engineering.',
        website: 'https://www.unimelb.edu.au',
        courses: ['Business', 'Engineering', 'Medicine', 'Data Science'],
        ranking: 33,
        fees: 32000,
        currency: 'AUD',
        logo: '',
        eligibility: { min_cgpa: 3.4, ielts: 6.5, gre: 0, entry_test: 'No' },
        visa_time: '5 Weeks',
        applicationDeadline: null,
        scholarships: ['Melbourne International Scholarship', 'Graduate Research Scholarship'],
        living_cost: 16000,
        isActive: true,
      },
      {
        _id: objectId('64f00000000000000000000a'),
        name: 'University of Sydney',
        country: 'Australia',
        city: 'Sydney',
        description: 'A top Australian university known for innovation, healthcare, and world-class teaching quality.',
        website: 'https://www.sydney.edu.au',
        courses: ['Business', 'Health Sciences', 'Engineering', 'Computer Science'],
        ranking: 29,
        fees: 34000,
        currency: 'AUD',
        logo: '',
        eligibility: { min_cgpa: 3.3, ielts: 6.5, gre: 0, entry_test: 'No' },
        visa_time: '5 Weeks',
        applicationDeadline: null,
        scholarships: ['Sydney Scholars Award', 'International Research Scholarship'],
        living_cost: 15000,
        isActive: true,
      },
    ];

    const visaRequirements = [
      {
        fromCountry: 'Pakistan',
        toCountry: 'United States',
        visaType: 'Student Visa',
        processingTimeMin: 14,
        processingTimeMax: 30,
        cost: 185,
        validityPeriod: 'Duration of study',
        requirements: ['Valid passport', 'Form I-20 from the university', 'DS-160 confirmation', 'Proof of sufficient funds', 'SEVIS fee payment receipt'],
        documents: ['Passport', 'I-20', 'DS-160 confirmation', 'SEVIS fee receipt', 'Financial statements'],
        proofOfFundsAmount: 30000,
        tuitionCoverageRequired: true,
        scholarshipAccepted: true,
        workRestrictionsPerWeek: 20,
        allowedDuringStudies: true,
        postStudyWorkVisa: { available: true, durationMonths: 36 },
        officialWebsite: 'https://travel.state.gov',
        applicationLink: 'https://ceac.state.gov/ceac/',
        embassy: 'US Embassy',
        difficultyLevel: 'Medium',
        description: 'Student visa process for studying in the United States.',
        tips: ['Prepare for the visa interview', 'Show strong financial documents', 'Apply early'],
        source: 'Manual',
        isActive: true,
      },
      {
        fromCountry: 'Pakistan',
        toCountry: 'United Kingdom',
        visaType: 'Student Visa',
        processingTimeMin: 21,
        processingTimeMax: 45,
        cost: 490,
        validityPeriod: 'Duration of study',
        requirements: ['Valid passport', 'CAS letter from the university', 'Proof of funds', 'Tuberculosis test result', 'Completed visa application form'],
        documents: ['Passport', 'CAS letter', 'Proof of funds', 'TB test result', 'Academic certificates'],
        proofOfFundsAmount: 25000,
        tuitionCoverageRequired: true,
        scholarshipAccepted: true,
        workRestrictionsPerWeek: 20,
        allowedDuringStudies: true,
        postStudyWorkVisa: { available: true, durationMonths: 24 },
        officialWebsite: 'https://www.gov.uk/student-visa',
        applicationLink: 'https://www.gov.uk/student-visa/apply',
        embassy: 'UK Visa and Immigration',
        difficultyLevel: 'Medium',
        description: 'Student visa process for studying in the United Kingdom.',
        tips: ['Apply as early as possible', 'Ensure your CAS details are correct', 'Keep funds documented'],
        source: 'Manual',
        isActive: true,
      },
    ];

    const aiToolData = [
      {
        name: 'SOP Generator',
        category: 'AI Tools',
        description: 'Generate a university-specific statement of purpose from user profile details.',
        isActive: true,
      },
      {
        name: 'Resume Builder',
        category: 'AI Tools',
        description: 'Create a tailored student resume with academic, leadership, and project highlights.',
        isActive: true,
      },
      {
        name: 'Scholarship Matcher',
        category: 'AI Tools',
        description: 'Identify the best scholarships based on CGPA, field, country, and budget.',
        isActive: true,
      },
    ];

    await University.insertMany(universities);
    await VisaRequirement.insertMany(visaRequirements);
    await mongoose.connection.db.collection('ai_tools').insertMany(aiToolData);

    console.log(`✅ Seeded ${universities.length} universities, ${visaRequirements.length} visa requirements, and ${aiToolData.length} AI tool entries`);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
};

seedData();
